{{ config(enabled=var('event_source_adapter', 'synthetic_flat') == 'synthetic_flat') }}

select
  cast(schema_version as string) as schema_version,
  'synthetic_flat' as source_system,
  'synthetic' as data_origin,
  cast(event_id as string) as event_id,
  date(event_date) as event_date,
  cast(event_timestamp as timestamp) as event_at,
  cast(event_name as string) as event_name,
  cast(user_pseudo_id as string) as user_pseudo_id,
  cast(session_id as string) as session_id,
  cast(page_type as string) as page_type,
  cast(journey_stage as string) as journey_stage,
  cast(device_category as string) as device_category,
  cast(traffic_source as string) as traffic_source,
  cast(traffic_medium as string) as traffic_medium,
  cast(campaign_id as string) as campaign_id,
  cast(campaign_name as string) as campaign_name,
  cast(entry_point as string) as entry_point,
  cast(comparison_model as string) as comparison_model,
  cast(specification_section as string) as specification_section,
  cast(offer_id as string) as offer_id,
  cast(cta_id as string) as cta_id,
  cast(vehicle_model as string) as vehicle_model,
  cast(vehicle_variant as string) as vehicle_variant,
  cast(powertrain as string) as powertrain,
  cast(configurator_id as string) as configurator_id,
  cast(configurator_step as string) as configurator_step,
  cast(configurator_value_band as string) as configurator_value_band,
  cast(colour_id as string) as colour_id,
  cast(option_ids as string) as option_ids,
  cast(loan_term_months as int64) as loan_term_months,
  cast(repayment_band as string) as repayment_band,
  cast(dealer_id as string) as dealer_id,
  cast(dealer_state as string) as dealer_state,
  cast(search_method as string) as search_method,
  cast(form_type as string) as form_type,
  cast(form_instance_id as string) as form_instance_id,
  cast(web_submission_id as string) as web_submission_id,
  cast(lead_id_hash as string) as lead_id_hash,
  cast(form_field as string) as form_field,
  cast(form_error_type as string) as form_error_type,
  cast(form_completion_time_seconds as double) as form_completion_time_seconds,
  cast(form_error_count as int64) as form_error_count,
  cast(experiment_id as string) as experiment_id,
  cast(experiment_assignment_id as string) as experiment_assignment_id,
  cast(variant_id as string) as variant_id,
  cast(audience_id as string) as audience_id,
  cast(personalisation_assignment_id as string) as personalisation_assignment_id,
  cast(experience_id as string) as experience_id,
  cast(holdout_flag as bool) as holdout_flag,
  cast(consent_analytics as string) as consent_analytics,
  cast(consent_marketing as string) as consent_marketing,
  cast(cmp_version as string) as cmp_version,
  cast(lead_status as string) as lead_status,
  cast(order_value_band as string) as order_value_band
from {{ source('raw_synthetic', 'events_flat') }}
