drive_to_joy:
  target: ci
  outputs:
    ci:
      type: bigquery
      method: oauth
      project: synthetic-ci-project
      dataset: analytics_ci
      threads: 1
      location: australia-southeast1
    local:
      type: duckdb
      path: data/processed/drive_to_joy_local.duckdb
      threads: 4
